image: node:16

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - chmod +x ./node_modules/.bin/tsc
  - chmod +x ./node_modules/.bin/jest

stages:
  - build
  - test

build:
  stage: build
  script:
    - which tsc
    - ./node_modules/.bin/tsc

test:
  stage: test
  script:
    - ./node_modules/.bin/jest --ci
